version: '3.4'

services: 
    basket-api:
        image: ${DOCKER_REGISTRY-}basketapi
        restart: always
        build:
            context: .
            dockerfile: Services/Basket/Basket.API/Dockerfile
        depends_on:
            - db
            - catalog-api
            
    catalog-api:
        image: ${DOCKER_REGISTRY-}catalogapi
        restart: always
        build:
            context: .
            dockerfile: Services/Catalog/Catalog.API/Dockerfile
        depends_on: 
            - db
            
    favorite-api:
        image: ${DOCKER_REGISTRY-}favoriteapi
        restart: always
        build: 
            context: .
            dockerfile: Services/Favorite/Favorite.API/Dockerfile
        depends_on:
            - db
            - catalog-api
            
    order-api:
        image: ${DOCKER_REGISTRY-}orderapi
        restart: always
        build: 
            context: .
            dockerfile: Services/Order/Order.API/Dockerfile
        depends_on:
            - db
            - catalog-api
            
    db: 
        image: mcr.microsoft.com/mssql/server:2019-latest 
        
    client: 
        image: ${DOCKER_REGISTRY-}client
        restart: always
        build:
            context: .
            dockerfile: ./UI/wigwamshop.frontend/Dockerfile
        depends_on:
        - catalog-api
